CREATE TABLE [silver].[risk_osd_item] (

	[osd_item_attached_record_code] float NULL, 
	[osd_item_item_record_code] float NULL, 
	[osd_item_discrepancy_type_code] float NULL, 
	[osd_item_damage_type_code] float NULL, 
	[osd_item_disposition_code] float NULL, 
	[osd_item_damage_cause_code] float NULL, 
	[osd_item_quantity] int NULL, 
	[osd_item_unit_of_measure_code] float NULL, 
	[osd_item_product_code] varchar(8000) NULL, 
	[osd_item_product_description] varchar(8000) NULL, 
	[osd_item_commodity_code] varchar(8000) NULL, 
	[osd_item_stopoff] varchar(8000) NULL, 
	[osd_item_return_fee_amount] float NULL, 
	[osd_item_expected_weight] varchar(8000) NULL, 
	[osd_item_delivered_weight] varchar(8000) NULL, 
	[osd_item_expected_condition_code] float NULL, 
	[osd_item_delivered_condition_code] float NULL, 
	[osd_item_comments] varchar(8000) NULL, 
	[osd_item_created_datetime] datetime2(6) NULL, 
	[osd_item_created_by_user_code] varchar(8000) NULL, 
	[osd_item_last_updated_datetime] datetime2(6) NULL, 
	[osd_item_last_updated_by_user_code] varchar(8000) NULL, 
	[osd_item_quantity_refused] int NULL, 
	[osd_item_quantity_damaged] int NULL, 
	[osd_item_quantity_over] int NULL, 
	[osd_item_quantity_short] int NULL, 
	[osd_item_quantity_kept] int NULL
);